### ISSUE TITLE
Travel log / Form

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project#1]
### Value statement
---

As a **traveler**
I need a way to **log** and remember my **adventures**
so that I can **recall** them in the future  

### Description (Text, Scribble, Wireframe, Design)

the form has 4 text-fields:
     - _date, city, caption_ and the chosen _category_ (at this stage, there will only be one category - memory)

<img width="440" alt="2Day_sprint_form" src="https://user-images.githubusercontent.com/65188676/86334074-04f6ac80-bc4d-11ea-9b5b-4a2c0985176d.png">

### Acceptance criteria
___

- [x] form fields are styled and have a good size with easy to read text

- [x] The selected / focused field will be highlighted 

- [x] The Submit Button is clickable

### Tasks
---
- [x] set up project with React, React Hook Form and styled-components

- [x] create feature branch

- [x] create form field and button in storybook

- [x]  Write component tests

- [x]  Add components to app (feature implementation with state)

- [x]  Add missing styles

### Size
---
medium
