### ISSUE TITLE
DetailsPage

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project#11]
### Value statement
---
As a an App User
I need a detailspage for my JournalEntries
to make them more readable 

### Description (Text, Scribble, Wireframe, Design)
---
<img width="367" alt="Bildschirmfoto 2020-07-19 um 21 30 12" src="https://user-images.githubusercontent.com/65188676/87883343-0a067a80-ca07-11ea-934b-20cdaaea9fcb.png">

DetailsPage with image header and unshortened memory section

### Acceptance criteria
---

- [x] click on JournalEntry will open the DetailsPage

- [x] image header with "go back" link to dashboard

- [x] styled details area with readable paragraphs

### Task
---

- [ ] Create JournalDetailsPage.js and stories

- [ ] Router/Switch between JournalEntries and DetailsPage

- [ ] Get data from selected entry and displaying it on the DetailsPaage

- [ ] create mock image until photoupload is possible to users

- [ ] Add Styling to match the rest of the App

### size
---
medium
