### ISSUE TITLE
TabBar

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project#12]
### Value statement
---
As an App User
I need a TabBar 
to be able to navigate between the different pages

### Description (Text, Scribble, Wireframe, Design)
---
<img width="610" alt="Bildschirmfoto 2020-07-19 um 21 43 49" src="https://user-images.githubusercontent.com/65188676/87883614-f0fec900-ca08-11ea-8a8d-bc3d9336713c.png">

TabBar with icons as links matching the appearance of the App

### Acceptance criteria
---
- [x]  icons are clickable and route to the different pages of the App

- [x] TabBar matches the appearance of the App

### Task
---

- [x] creating TabBar.js

- [x] adding icons 

- [x] Routing between the pages

- [x] add Storybook
