### ISSUE TITLE
Local storage for JournalForm

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project#4]

**Comment by franhenke** [comment]
### Value statement
---

As a **developer
I need a **local storage**
to **store and display** the values of the JournalForm 
until I have a working backend

### Description (Text, Scribble, Wireframe, Design)

The input made in the JournalForm will be stored in the local storage and displayed underneath the form

### Acceptance criteria

- [ ] input made in the JournalForm will be stored

- [ ] input value is shown underneath the form

- [ ] data won't be deleted after refreshing the app

### Task

- [ ] implement local storage to the form

- [ ] persisting local storage so that I can reload the site without the entries disappearing

- [ ] useEffect to make the storage render only when there are no existing JournalEntries yet

### Size
small
