### ISSUE TITLE
Add Categories to JournalForm

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project#7]
### Value statement
---
as an App User,
I need to categorize my JournalEntries
so that I can filter them

Description (Text, Scribble, Wireframe, Design)
---

3 Categories: Memory, Review, Thoughts
Dropdown 

<img width="322" alt="Bildschirmfoto 2020-07-14 um 22 37 25" src="https://user-images.githubusercontent.com/65188676/87473969-9a694780-c622-11ea-833b-dad632d2dafc.png">

### Acceptance criteria
---

- [x] 3 Categories
- [x] style matches the app
- [x] selected category will be rendered and displayed in JournalEntry

### Tasks
---

- [x] create a <select> element into the JournalForm

- [ ] add the 3 categories as options

- [ ] Update JournalEntry.js

- [ ] Add styling and visualize in storybook

### Size
small
