### ISSUE TITLE
Router between Welcome & Dashboard

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project#8]
### Value statement
---
as an App User,
I need to be directed to the Dashboard of the app
to see my JournalEntries and to create a new one

Description (Text, Scribble, Wireframe, Design)
---

Form will open after clicking the arrow icon on the welcome page.
A router will create a path and add it to the URL.

<img width="541" alt="Bildschirmfoto 2020-07-14 um 23 47 17" src="https://user-images.githubusercontent.com/65188676/87479791-5da24e00-c62c-11ea-9247-186582206205.png">

### Acceptance criteria
---

- [x] user will be directed to the dashboard by a click of the arrow icon

- [x] url will change to the directed path

### Task
---

- [x] install Router

- [x] create Dashboard.js

- [x] create route and path between Welcome Page and Dashboard

### Size
---
small
